baseURL = "https://Sintaxine.github.io/blog/"

title = "Sin's Blog"
paginate = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema
  title = "Sin's Blog"
  description = "tech blog blog site thingie thingie yeah lol"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Sin"
  # author = ["Me", "You"] # multiple authors
  images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    # disableHLJS = true # to disable highlight.js
    # disableFingerprinting = true
    favicon = "/home/yassine/quickstart/assets/favicon_io/favicon-32x32.png"
    favicon16x16 = "/home/yassine/quickstart/assets/favicon_io/favicon-16x16.png"
    favicon32x32 = "/home/yassine/quickstart/assets/favicon_io/favicon-32x32.png"
    apple_touch_icon = "/home/yassine/quickstart/assets/favicon_io/apple-touch-icon.png"
    safari_pinned_tab = "/home/yassine/quickstart/assets/favicon_io/apple-touch-icon.png"

  [params.label]
    text = "Home"
    icon = "/home/yassine/quickstart/assets/favicon_io/apple-touch-icon.png"
    iconHeight = 35

  [params.profileMode]
    enabled = false # needs to be explicitly set
    title = "Sin's Blog"
    subtitle = "This is subtitle"
    imageUrl = "<img location>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "Tags"
      url = "tags"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my tech/cybersec blog"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mikusshit"

  [params.analytics.google]
    SiteVerificationTag = "XYZabc"

  [params.analytics.bing]
    SiteVerificationTag = "XYZabc"

  [params.analytics.yandex]
    SiteVerificationTag = "XYZabc"

  [params.cover]
    hidden = true # hide everywhere but not in structured data
    hiddenInList = true # hide on list pages and home
    hiddenInSingle = true # hide on single page

  [params.editPost]
    URL = "https://github.com/<path_to_repo>/content"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys = ["title", "permalink", "summary", "content"]

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20


pygmentsUseClasses = true

[markup.highlight]
  noClasses = false
  # anchorLineNos = true
  # codeFences = true
  # guessSyntax = true
  # lineNos = true
  # style = "monokai"

